# Buenas Practicas para nombres de variables

In [1]:
priceearnings = 12

In [ ]:
# price_earnings = 12

In [ ]:
# priceEarnings = 12

 * significado: que el nombre de la variable sea representativo de lo que tiene
 * longitud: ni mucho ni poco
 * usos y constumbres: camelCase, snake_case
 * empiezan con minuscula

# Estructuras de datos en python

## Estructuras Nativas

Datos estructurados (machete rápido)

* Corchetes > Listas
* Parentesis > Tuplas  (Inalterables)
* Llaves > Diccionarios

# Estructuras no nativas

* Numpy Arrays 
* DataFrames
* Dask Arrays/DataFRames

etc

# Listas

Las listas son simplemente un conjunto de datos y se lo define entre corchetes con sus elementos separados con coma

# Listas

In [2]:
caja = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
caja[ 2:6 ]

[3, 4, 5, 6]

caja [ desde_inclusive : hasta_exclusive ]   

In [4]:
caja[0] = 'Nuevo Elemento'


In [5]:
caja

['Nuevo Elemento', 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
len(caja)

10

In [7]:
caja[0]

'Nuevo Elemento'

In [8]:
caja[1]

2

In [9]:
caja[-1]

10

## Lista Vacia

Una lista vacía se la escribe así

In [10]:
lista_vacia = list()
lista_vacia

[]

O así

In [11]:
lista_vacia = []
lista_vacia

[]

In [12]:
type(lista_vacia)

list

## Asignar valores a una lista

In [13]:
lista_str = ['Yo','me','llamo','Juan']
lista_str

['Yo', 'me', 'llamo', 'Juan']

In [14]:
lista_comb = ['Yo','me','llamo','Juan', 1,2,3, False, True]
lista_comb

['Yo', 'me', 'llamo', 'Juan', 1, 2, 3, False, True]

In [15]:
type(lista_comb)

list

## "Sumar" listas

In [16]:
numero1 = 10
numero2 = 20

reultado_suma = numero1 + numero2
reultado_suma

30

In [17]:
numero1 = [10]
numero2 = [20]

reultado_suma = numero1 + numero2
reultado_suma

[10, 20]

In [18]:
lista1 = [10,11,12,13,14,15]
lista2 = [20,21,22,23,24]

reultado_suma = lista1[0] + lista2[3]
reultado_suma

33

## Funciones de listas

In [19]:
lista = [1,2,3,4]
sum(lista)

10

In [20]:
len(lista)

4

### Append

In [21]:
lista.append(5)

In [22]:
lista

[1, 2, 3, 4, 5]

In [23]:
lista.append([6,7,8])

In [24]:
lista

[1, 2, 3, 4, 5, [6, 7, 8]]

### Insert

In [25]:
help(list.insert)

Help on method_descriptor:

insert(self, index, object, /)
    Insert object before index.



In [26]:
lista.insert(2,'Juan')

In [27]:
lista

[1, 2, 'Juan', 3, 4, 5, [6, 7, 8]]

### Pop

In [28]:
lista.pop()

[6, 7, 8]

In [29]:
lista

[1, 2, 'Juan', 3, 4, 5]

In [30]:
variable = lista.pop(2)

In [31]:
lista

[1, 2, 3, 4, 5]

In [32]:
variable

'Juan'

In [33]:
help(list.pop)

Help on method_descriptor:

pop(self, index=-1, /)
    Remove and return item at index (default last).
    
    Raises IndexError if list is empty or index is out of range.



### Mas funciones de listas

In [34]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## Listas "complejas"

In [35]:
lista = ['FB', 'AAPL', 'AMZN','NFLX','GOOGL', [1,2,3,4,5,6,7,8], True]
lista

['FB', 'AAPL', 'AMZN', 'NFLX', 'GOOGL', [1, 2, 3, 4, 5, 6, 7, 8], True]

In [36]:
lista[-1]

True

In [37]:
lista[-2]

[1, 2, 3, 4, 5, 6, 7, 8]

## Intervalos

[ desde : hasta : paso ]

* El desde siempre es inclusive
* El hasta es siempre exclusive

In [38]:
lista = [23,6,3,9,4,12,0]

lista[1:4]

[6, 3, 9]

In [39]:
lista[1:4:2]

[6, 9]

In [40]:
# [desde_inclusive : hasta_exclusive : step o paso]

In [41]:
lista = [0,1,2,3,4,5,6,7,8,9,10]

lista[4:]

[4, 5, 6, 7, 8, 9, 10]

In [42]:
lista[:6]

[0, 1, 2, 3, 4, 5]

In [43]:
lista[0:10:3]

[0, 3, 6, 9]

## Ejercicio, tratemos de imaginar que devuelve esto..

In [ ]:
#lista[::3]

In [ ]:
#lista[::2]

In [ ]:
#lista[1::2]

In [ ]:
#lista[::-1]

In [ ]:
#lista[::-2]

In [ ]:
#lista[:-2]

In [ ]:
#lista[:3]+lista[:2]

In [ ]:
#a = 4
#lista[a:-1]

In [ ]:
#desde_inc = 3
#hasta_exc = 7
#paso = 1

#lista[desde_inc : hasta_exc : paso]

# Generadores

In [44]:
range(0,10,1)

range(0, 10)

In [45]:
rango = range(0,10,1)

lista = list(rango)
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
rango

range(0, 10)

In [47]:
tabla7_hasta_200 = list(range(0,200,7))


tabla7_hasta_200[:5]

[0, 7, 14, 21, 28]

# Listas por comprension

In [1]:
lista = [i for i in range(10)]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
lista = [2*x+1 for x in range(10)]
lista

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

# Tuplas

In [48]:
tupla = (1,2,3,4)

tupla[0]

1

In [49]:
tupla[0] = 'Juan'

TypeError: 'tuple' object does not support item assignment

In [ ]:
type(tupla)

In [50]:
tupla

(1, 2, 3, 4)

# ¿y si quiero operar algebraicamente con listas?

In [51]:
precios = [23.1, 23.3, 23.2, 23, 23.25]

preciosUp = precios * 1.05
preciosUp

TypeError: can't multiply sequence by non-int of type 'float'

# Operatoria Matricial (con Numpy)

In [52]:
import numpy as np

In [53]:
precios = [23.1, 23.3, 23.2, 23, 23.25]

precios = np.array(precios)
precios

array([23.1 , 23.3 , 23.2 , 23.  , 23.25])

In [54]:
preciosUp = precios * 1.05
preciosUp

array([24.255 , 24.465 , 24.36  , 24.15  , 24.4125])

In [55]:
precios.std()

0.10770329614269003

In [56]:
np.std(precios)

0.10770329614269003

In [57]:
np.median(precios)

23.2

In [58]:
precios.mean()

23.17

In [59]:
preciosUp.mean()

24.328500000000002

In [60]:
preciosUp.var()

0.012789

## Numeros aleatorios con Numpy

In [61]:
np.random.seed(0)
np.random.normal(0,1,10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [62]:
np.random.seed(0)
np.random.normal(loc=0, scale=1, size=10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [63]:
np.random.normal(loc=0, scale=1, size=(5,4)).round(3)

array([[ 0.144,  1.454,  0.761,  0.122],
       [ 0.444,  0.334,  1.494, -0.205],
       [ 0.313, -0.854, -2.553,  0.654],
       [ 0.864, -0.742,  2.27 , -1.454],
       [ 0.046, -0.187,  1.533,  1.469]])

In [64]:
np.random.normal(loc=0, scale=1, size=5000).round(3).std()

0.9851551820012926

## Generadores de numpy

In [65]:
np.random.uniform(low=-10, high=10, size=10).round(3)

array([ 1.749, -1.368, -6.822, -7.489, -5.746,  2.107,  0.931, -3.428,
       -9.117, -3.519])

In [66]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
np.random.random(size=(3,5))

array([[0.39830332, 0.75642378, 0.73748399, 0.2214081 , 0.22767395],
       [0.62788283, 0.65177635, 0.56110278, 0.11197138, 0.28572015],
       [0.03170321, 0.76159415, 0.80650343, 0.9204806 , 0.08791557]])

In [68]:
np.random.normal(0,1,size=(4,2))

array([[-0.89355842, -0.90084923],
       [ 1.11613048,  1.16881702],
       [-1.23282105,  1.34571339],
       [-1.90767706,  0.19025861]])

In [69]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [70]:
np.linspace(0,2,10, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

## Ciclo FOR

In [71]:
print(1)
print(2)
print(3)

1
2
3


In [72]:
for i in range(3):
    print(i)

0
1
2


In [76]:
import time, datetime

print(datetime.datetime.now())

for i in range(3):
    time.sleep(1)
    print(datetime.datetime.now())

2021-03-17 06:09:27.008217
2021-03-17 06:09:28.022850
2021-03-17 06:09:29.025098
2021-03-17 06:09:30.038286


In [75]:
import random

precio = 100

for i in range(10):
    
    precio *= 1 + random.normalvariate(mu=0, sigma=1.5)/100
    
    print(f'Simulacion N°{i+1}, precio ${precio:.2f}')
    
print(f'\n{"-"*30} \nFin de simulaciones\n{"-"*30}')

Simulacion N°1, precio $100.16
Simulacion N°2, precio $98.01
Simulacion N°3, precio $98.82
Simulacion N°4, precio $96.83
Simulacion N°5, precio $96.55
Simulacion N°6, precio $97.56
Simulacion N°7, precio $98.86
Simulacion N°8, precio $97.62
Simulacion N°9, precio $97.23
Simulacion N°10, precio $96.67

------------------------------ 
Fin de simulaciones
------------------------------
