# Buenas Practicas para nombres de variables

In [1]:
x1, x2, x3 = 12 , 15.8, 2021

In [6]:
PRICE_EARNINGS = 12

In [2]:
priceearnings = 12

In [3]:
price_earnings = 12

In [5]:
priceEarnings = 12

 * significado: que el nombre de la variable sea representativo de lo que tiene
 * longitud: ni mucho ni poco
 * usos y constumbres: camelCase, snake_case
 * empiezan con minuscula

# Estructuras de datos en python

## Estructuras Nativas

Datos estructurados (machete rápido)

* Corchetes > Listas
* Parentesis > Tuplas  (Inalterables)
* Llaves > Diccionarios

# Estructuras no nativas

* Numpy Arrays 
* DataFrames
* Dask Arrays/DataFRames

etc

# Listas

Las listas son simplemente un conjunto de datos y se lo define entre corchetes con sus elementos separados con coma

# Listas

In [14]:
caja = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
caja[4:10:3]   # output 4 y 7

[4, 7]

In [38]:
caja[4:][::3][:2]

[4, 7]

In [41]:
caja[4:][::3][:2]

[4, 7]

In [15]:
caja[ 2 : 6 ]

[2, 3, 4, 5]

In [16]:
caja[ : : 2 ]

[0, 2, 4, 6, 8, 10]

In [19]:
caja [-4]

7

In [22]:
caja[4:0:-1]

[4, 3, 2, 1]

In [23]:
caja[11]

IndexError: list index out of range

In [26]:
caja[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [28]:
caja[0:10:-1]

[]

In [30]:
caja[0::-1]

[0]

In [32]:
caja[0::-1]

[0]

caja [ desde_inclusive : hasta_exclusive ]   

In [42]:
caja

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [43]:
caja[0] = 'Nuevo Elemento'
caja

['Nuevo Elemento', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [44]:
len(caja)

11

In [46]:
caja[0:4:2]

['Nuevo Elemento', 2]

In [8]:
caja[1]

2

In [9]:
caja[-1]

10

## Lista Vacia

Una lista vacía se la escribe así

In [10]:
lista_vacia = list()
lista_vacia

[]

O así

In [47]:
lista_vacia = []
lista_vacia

[]

In [48]:
type(lista_vacia)

list

## Asignar valores a una lista

In [49]:
lista_str = ['Yo','me','llamo','Juan']
lista_str

['Yo', 'me', 'llamo', 'Juan']

In [50]:
lista_comb = ['Yo','me','llamo','Juan', 1,2,3, False, True]
lista_comb

['Yo', 'me', 'llamo', 'Juan', 1, 2, 3, False, True]

In [51]:
type(lista_comb)

list

In [53]:
lista_comb[0] = lista_str

In [54]:
lista_comb

[['Yo', 'me', 'llamo', 'Juan'], 'me', 'llamo', 'Juan', 1, 2, 3, False, True]

In [55]:
lista_str[3] = 'Pablo'
lista_str

['Yo', 'me', 'llamo', 'Pablo']

In [56]:
lista_comb

[['Yo', 'me', 'llamo', 'Pablo'], 'me', 'llamo', 'Juan', 1, 2, 3, False, True]

## "Sumar" listas

In [1]:
st1 = 'Juan'
st2 = 'Pablo'

st1 + st2

'JuanPablo'

In [2]:
l1 = [1,2,3,4,5]
l2 = [1,2,3,4,5]

l1 + l2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
1 + 'Juan'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [8]:
l1 * 2 + 1

TypeError: can only concatenate list (not "int") to list

In [9]:
l1[3] + l2[0]

5

In [10]:
l3 = [[1,2], [5,6]]

l1[3] + l3[0]

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [11]:
l1 * l2

TypeError: can't multiply sequence by non-int of type 'list'

In [57]:
numero1 = 10
numero2 = 20

reultado_suma = numero1 + numero2
reultado_suma

30

In [12]:
numero1 = [10, 2, 30]
numero2 = [20, 'juan', [1,2,3]]

reultado_suma = numero1[0] + numero2[2][1]
reultado_suma

12

In [13]:
lista = [0,1,2, [0,1,2, [0,1,2] ]  ]
lista

[0, 1, 2, [0, 1, 2, [0, 1, 2]]]

In [14]:
lista[3]

[0, 1, 2, [0, 1, 2]]

In [15]:
lista[3][3]

[0, 1, 2]

In [17]:
lista[3][3][2]

2

In [69]:
numero1 + numero2[2]

[10, 2, 30, 1, 2, 3]

In [61]:
numero1[0] + numero2[0]

30

In [64]:
numero2[0:1:1]

[20]

In [67]:
numero1[:]

[10, 2, 30]

In [68]:
numero2[0]

20

In [66]:
numero1[:] + numero2[0]

TypeError: can only concatenate list (not "int") to list

In [60]:
lista1 = [10,11,12,13,14,15]
lista2 = [20,21,22,23,24]

reultado_suma = lista1[0] + lista2[3]
reultado_suma

33

## Funciones de listas

In [18]:
lista = [1,2,3,4]
sum(lista)

10

In [19]:
len(lista)

4

In [20]:
sum(lista)/len(lista)

2.5

### Append

In [25]:
lista.append(5)

In [26]:
lista

[1, 2, 3, 4, 5, 5, 5]

In [27]:
lista.append([6,7,8])

In [28]:
lista

[1, 2, 3, 4, 5, 5, 5, [6, 7, 8]]

### Insert

In [31]:
lista.insert(0,0)

In [32]:
lista

[0, 1, 2, 3, 4, 5, 5, 5, [6, 7, 8]]

In [29]:
help(list.insert)

Help on method_descriptor:

insert(self, index, object, /)
    Insert object before index.



In [30]:
help(lista.insert)

Help on built-in function insert:

insert(index, object, /) method of builtins.list instance
    Insert object before index.



In [26]:
lista.insert(2,'Juan')

In [27]:
lista

[1, 2, 'Juan', 3, 4, 5, [6, 7, 8]]

### Pop

In [33]:
# extrae el ultimo elemento de la lista (lo saca) y me lo devuelve como return

In [34]:
resultado = lista.append(12)
resultado

In [35]:
print(resultado)

None


In [36]:
lista

[0, 1, 2, 3, 4, 5, 5, 5, [6, 7, 8], 12]

In [37]:
resultado_pop = lista.pop()
resultado_pop

12

In [38]:
lista

[0, 1, 2, 3, 4, 5, 5, 5, [6, 7, 8]]

In [39]:
lista.pop()

[6, 7, 8]

In [42]:
lista

[0, 1, 2, 3, 4, 5, 5, 5]

In [43]:
len(lista)

8

In [44]:
help(list.pop)

Help on method_descriptor:

pop(self, index=-1, /)
    Remove and return item at index (default last).
    
    Raises IndexError if list is empty or index is out of range.



In [45]:
lista

[0, 1, 2, 3, 4, 5, 5, 5]

In [46]:
variable = lista.pop(1)

In [47]:
lista, variable

([0, 2, 3, 4, 5, 5, 5], 1)

In [50]:
n = 'Juan'
n[-2]

'a'

In [33]:

help(list.pop)

Help on method_descriptor:

pop(self, index=-1, /)
    Remove and return item at index (default last).
    
    Raises IndexError if list is empty or index is out of range.



### Mas funciones de listas

In [51]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [52]:
lista

[0, 2, 3, 4, 5, 5, 5]

In [53]:
lista[0] = 15
lista

[15, 2, 3, 4, 5, 5, 5]

## Listas "complejas"

In [35]:
lista = ['FB', 'AAPL', 'AMZN','NFLX','GOOGL', [1,2,3,4,5,6,7,8], True]
lista

['FB', 'AAPL', 'AMZN', 'NFLX', 'GOOGL', [1, 2, 3, 4, 5, 6, 7, 8], True]

In [36]:
lista[-1]

True

In [37]:
lista[-2]

[1, 2, 3, 4, 5, 6, 7, 8]

## Intervalos

[ desde : hasta : paso ]

* El desde siempre es inclusive
* El hasta es siempre exclusive

In [57]:
lista = [23,6,3,9,4,12,0]

lista[1:4]

[6, 3, 9]

In [55]:
lista[1:4:2]

[6, 9]

In [58]:
lista[2:15:2]

[3, 4, 0]

In [40]:
# [desde_inclusive : hasta_exclusive : step o paso]

In [41]:
lista = [0,1,2,3,4,5,6,7,8,9,10]

lista[4:]

[4, 5, 6, 7, 8, 9, 10]

In [42]:
lista[:6]

[0, 1, 2, 3, 4, 5]

In [43]:
lista[0:10:3]

[0, 3, 6, 9]

## Ejercicio, tratemos de imaginar que devuelve esto..

In [ ]:
#lista[::3]

In [ ]:
#lista[::2]

In [ ]:
#lista[1::2]

In [ ]:
#lista[::-1]

In [ ]:
#lista[::-2]

In [ ]:
#lista[:-2]

In [ ]:
#lista[:3]+lista[:2]

In [ ]:
#a = 4
#lista[a:-1]

In [59]:
lista

[23, 6, 3, 9, 4, 12, 0]

In [60]:
desde_inc = 3
hasta_exc = 7
paso = 1

lista[desde_inc : hasta_exc : paso]

[9, 4, 12, 0]

# Generadores

In [62]:
range(0,10,2)

range(0, 10, 2)

In [64]:
rango = range(0,10,2)

lista = list(rango)
lista

[0, 2, 4, 6, 8]

In [65]:
rango

range(0, 10, 2)

In [67]:
tabla7_hasta_200 = list(range(7,200,7))


tabla7_hasta_200

[7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 70,
 77,
 84,
 91,
 98,
 105,
 112,
 119,
 126,
 133,
 140,
 147,
 154,
 161,
 168,
 175,
 182,
 189,
 196]

# Listas por comprension

In [68]:
rango = range(0,10)
rango = range(10)
rango

range(0, 10)

In [71]:
x = 'juan'
lista = [x for x in range(10)]
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [72]:
lista = [2*x+1 for x in range(10)]
lista

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [73]:
x

'juan'

# Tuplas

In [74]:
lista = [1,2,3,4]

lista[0] = 'Juan'
lista

['Juan', 2, 3, 4]

In [75]:
tupla = (1,2,3,4)

tupla[0]

1

In [76]:
tupla[0] = 'Juan'

TypeError: 'tuple' object does not support item assignment

In [82]:
lista_1 = list(tupla)

In [84]:
lista_1 = tupla

In [86]:
lista_1

(1, 2, 3, 4)

In [77]:
tupla[1:3]

(2, 3)

In [79]:
type(lista)

list

In [78]:
type(tupla)

tuple

In [50]:
tupla

(1, 2, 3, 4)

In [96]:
#elemento_4 = [0,1]
tupla = (1,2,3 , elemento_4)
tupla

(1, 2, 3, 'Juan')

In [90]:
elemento_4 = 'Juan'
tupla

(1, 2, 3, [0, 1])

In [95]:
#elemento_4 = [0,1]
lista = [1,2,3 , elemento_4]
lista

[1, 2, 3, 'Juan']

In [94]:
elemento_4 = 'Juan'
lista

[1, 2, 3, [0, 1]]

# ¿y si quiero operar algebraicamente con listas?

In [97]:
precios = [23.1, 23.3, 23.2, 23, 23.25]

preciosUp = precios * 1.05
preciosUp

TypeError: can't multiply sequence by non-int of type 'float'

In [99]:
preciosUp = [ x * 1.05 for x in precios ]
preciosUp

[24.255000000000003, 24.465000000000003, 24.36, 24.150000000000002, 24.4125]

In [104]:
preciosUp = [ precios[i] * 1.05 for i in range(len(precios)) ]
preciosUp

[24.255000000000003, 24.465000000000003, 24.36, 24.150000000000002, 24.4125]

In [102]:
preciosUp = [ x for x in precios if x > 23.25 ]
preciosUp

[23.3]

# Operatoria Matricial (con Numpy)

In [106]:
import numpy as np

In [107]:
precios = [23.1, 23.3, 23.2, 23, 23.25]

precios = np.array(precios)
precios

array([23.1 , 23.3 , 23.2 , 23.  , 23.25])

In [108]:
k = 1.05

preciosUp = k * precios
preciosUp

array([24.255 , 24.465 , 24.36  , 24.15  , 24.4125])

In [116]:
lista = [1,2,3,4]
np_lista = np.array([1,2,3,4])

np_lista.std()

1.118033988749895

In [109]:
precios.std()   # al objeto precios (es un numpy array) le aplico el metodo std()

0.10770329614269003

In [113]:
np.std([1,2,3,4])   # del paquete numpy llamo a la funcion std() y le paso el argumento "lista"

1.118033988749895

In [118]:
np.median(precios)

23.2

In [119]:
precios.mean()

23.17

In [59]:
preciosUp.mean()

24.328500000000002

In [120]:
preciosUp.var()

0.012789

## Numeros aleatorios con Numpy

In [125]:
np.random.seed(0)

np.random.normal(0,1,10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [131]:
np.random.seed(0)

np.random.normal(0,1,size=(3,5,2))

array([[[ 1.76405235,  0.40015721],
        [ 0.97873798,  2.2408932 ],
        [ 1.86755799, -0.97727788],
        [ 0.95008842, -0.15135721],
        [-0.10321885,  0.4105985 ]],

       [[ 0.14404357,  1.45427351],
        [ 0.76103773,  0.12167502],
        [ 0.44386323,  0.33367433],
        [ 1.49407907, -0.20515826],
        [ 0.3130677 , -0.85409574]],

       [[-2.55298982,  0.6536186 ],
        [ 0.8644362 , -0.74216502],
        [ 2.26975462, -1.45436567],
        [ 0.04575852, -0.18718385],
        [ 1.53277921,  1.46935877]]])

In [62]:
np.random.seed(0)
np.random.normal(loc=0, scale=1, size=10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [63]:
np.random.normal(loc=0, scale=1, size=(5,4)).round(3)

array([[ 0.144,  1.454,  0.761,  0.122],
       [ 0.444,  0.334,  1.494, -0.205],
       [ 0.313, -0.854, -2.553,  0.654],
       [ 0.864, -0.742,  2.27 , -1.454],
       [ 0.046, -0.187,  1.533,  1.469]])

In [64]:
np.random.normal(loc=0, scale=1, size=5000).round(3).std()

0.9851551820012926

In [6]:
dist = np.random.normal(loc=0, scale=1, size=5000)
dist

array([ 1.65256443, -0.61980261,  0.52717806, ..., -0.79350784,
       -0.61231317,  0.67396542])

## Generadores de numpy

In [65]:
np.random.uniform(low=-10, high=10, size=10).round(3)

array([ 1.749, -1.368, -6.822, -7.489, -5.746,  2.107,  0.931, -3.428,
       -9.117, -3.519])

In [66]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
np.random.random(size=(3,5))

array([[0.39830332, 0.75642378, 0.73748399, 0.2214081 , 0.22767395],
       [0.62788283, 0.65177635, 0.56110278, 0.11197138, 0.28572015],
       [0.03170321, 0.76159415, 0.80650343, 0.9204806 , 0.08791557]])

In [68]:
np.random.normal(0,1,size=(4,2))

array([[-0.89355842, -0.90084923],
       [ 1.11613048,  1.16881702],
       [-1.23282105,  1.34571339],
       [-1.90767706,  0.19025861]])

In [69]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [70]:
np.linspace(0,2,10, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

## Ciclo FOR

$$  \Large  \sigma = \sqrt {\frac{1}{n} \sum_{i=1}^{n} (\mu - x_i)^2}  $$

In [133]:
print(1)
print(2)
print(3)

1
2
3


In [134]:
for i in range(3):
    print(i+1)

1
2
3


In [135]:
for i in range(1,4):
    print(i)   
    # este caso es sencillo pero aca podrian ir mas instrucciones
    # otra instruccion
    
# aca ya sali del ciclo FOR

1
2
3


In [137]:
import time, datetime

print('Esto es antes de entrar al FOR', datetime.datetime.now())

for i in range(3):
    time.sleep(1)
    print(datetime.datetime.now())

Esto es antes de entrar al FOR 2021-04-13 20:01:42.005228
2021-04-13 20:01:43.009647
2021-04-13 20:01:44.017538
2021-04-13 20:01:45.030693


In [138]:
precio = 100

precio = precio * 1.1
precio

110.00000000000001

In [139]:
precio = 100

precio *= 1.1
precio

110.00000000000001

In [140]:
i = 100

i += 1
i

101

In [148]:
random.seed(0)

random.normalvariate(mu=0, sigma=1.5)


-0.2758023316398874

In [147]:
import random

random.seed(0)

precio = 100
f = 1 + random.normalvariate(mu=0, sigma=1.5)/100

precio2 = precio * f

precio, f, precio2

(100, 0.9972419766836012, 99.72419766836012)

In [150]:
import random

precio = 100

for i in range(10):
    print(f'{precio:.2f}')
    precio *= 1 + random.normalvariate(mu=0, sigma=1.5)/100
    
    print(f'Simulacion N°{i+1}, precio ${precio:.2f}')
    
print(f'\n{"-"*30} \nFin de simulaciones\n{"-"*30}')

100.00
Simulacion N°1, precio $96.84
96.84
Simulacion N°2, precio $96.96
96.96
Simulacion N°3, precio $97.87
97.87
Simulacion N°4, precio $100.34
100.34
Simulacion N°5, precio $101.59
101.59
Simulacion N°6, precio $98.07
98.07
Simulacion N°7, precio $96.26
96.26
Simulacion N°8, precio $97.62
97.62
Simulacion N°9, precio $96.07
96.07
Simulacion N°10, precio $96.37

------------------------------ 
Fin de simulaciones
------------------------------


In [152]:
vd = 2

vanual = vd * 250**0.5
vanual

31.622776601683793

1- generar una dist aleatoria de retornos con mu=0 y sigma=2


2- calcular el desvio estandar con un ciclo FOR


3- hacer el mismo calculo vectorialmente

$$  \Large  \sigma = \sqrt {\frac{1}{n} \sum_{i=1}^{n} (\mu - x_i)^2}  $$

In [154]:
ret = []

for i in range(50):

    ret.append ( random.normalvariate(mu=0, sigma=2) )
    

In [155]:
ret = [ random.normalvariate(mu=0, sigma=2)  for i in range(50)]

In [159]:
ret = np.random.normal(0,2,50)

In [168]:
n = 5000
ret = [ random.normalvariate(mu=0, sigma=2)  for i in range(n)]

In [169]:
suma = 0
mu = sum(ret)/len(ret)

for i in range(len(ret)):
    suma += (mu - ret[i])**2
    

desvio = (suma/len(ret))**0.5
desvio

1.9774845900256075

In [193]:
%%timeit

mu = sum(ret)/len(ret)
valores_internos_sigma = []

for i in range(len(ret)):
    valores_internos_sigma. append ((mu - ret[i])**2)
    
sumatoria = sum(valores_internos_sigma)
desvio = (sumatoria/len(ret))**0.5
desvio

6.95 ms ± 181 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [192]:
ret = np.random.normal(0,2,5000)

$$  \Large  \sigma = \sqrt {\frac{1}{n} \sum_{i=1}^{n} (\mu - x_i)^2}  $$

In [176]:
# [1,2,3,4] + [0,0,0,1] = [1,2,3,5]

np.array([1,2,3,4]) + np.array([1,1,1,1])

array([2, 3, 4, 5])

In [196]:
%%timeit
mu = ret.sum()

( ((ret - mu)**2).sum() / len(ret) ) **0.5 

29.4 µs ± 3.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [189]:
((ret - mu)**2).sum()

19478.0460411385

In [195]:
%%timeit

ret.std()

54.9 µs ± 3.01 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [185]:
np.array([1,2,3,4]) + np.array([1,1,1,1])

array([2, 3, 4, 5])

In [187]:
np.array([1,2,3,4]) - 1

array([0, 1, 2, 3])